import { PointerEvent, useEffect, useMemo, useRef, useState } from "react";
import { Check, MousePointer2, Plus, RotateCcw, Save, Trash2 } from "lucide-react";
import { apiBase, request } from "../api";
import { ZoneConfig } from "../types";

const palette=["#22d3ee","#34d399","#f59e0b","#a78bfa","#fb7185"];

export default function ZoneEditor({cameraConnected}:{cameraConnected:boolean}) {
  const [zones,setZones]=useState<ZoneConfig[]>([]); const [selected,setSelected]=useState<number|null>(null); const [saving,setSaving]=useState(false);
  const drag=useRef<{id:number;x:number;y:number;coords:{x:number;y:number}[]}|null>(null);
  useEffect(()=>{request<ZoneConfig[]>("/api/zones").then(value=>{setZones(value);setSelected(value[0]?.id??null)}).catch(()=>undefined)},[]);
  const active=useMemo(()=>zones.find(z=>z.id===selected),[zones,selected]);
  function pointerDown(event:PointerEvent,id:number){const z=zones.find(i=>i.id===id);if(!z)return; (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);drag.current={id,x:event.clientX,y:event.clientY,coords:z.coordinates.map(p=>({...p}))};setSelected(id)}
  function pointerMove(event:PointerEvent){if(!drag.current)return;const host=(event.currentTarget as HTMLElement).parentElement!;const dx=(event.clientX-drag.current.x)/host.clientWidth;const dy=(event.clientY-drag.current.y)/host.clientHeight;setZones(zones=>zones.map(z=>z.id===drag.current!.id?{...z,coordinates:drag.current!.coords.map(p=>({x:Math.max(0,Math.min(1,p.x+dx)),y:Math.max(0,Math.min(1,p.y+dy))}))}:z))}
  function pointerUp(){drag.current=null}
  async function save(){setSaving(true);try{for(const z of zones)await request(`/api/zones/${z.id}`,{method:"PUT",body:JSON.stringify(z)});}finally{setSaving(false)}}
  async function reset(){if(!confirm("Restore the three default zones? Custom zones will be removed."))return;setZones(await request("/api/zones/reset-default",{method:"POST"}));}
  function add(){const next=Math.max(0,...zones.map(z=>z.id))+1;const z:ZoneConfig={id:next,name:`Zone ${next}`,colour:palette[zones.length%palette.length],enabled:true,zone_type:"rectangle",coordinates:[{x:.35,y:.3},{x:.65,y:.3},{x:.65,y:.75},{x:.35,y:.75}],relay_ids:[],auto_control_enabled:true};request<{id:number}>("/api/zones",{method:"POST",body:JSON.stringify({...z,id:undefined})}).then(saved=>{z.id=saved.id;setZones(v=>[...v,z]);setSelected(z.id)})}
  async function remove(){if(!active||!confirm(`Delete ${active.name}?`))return;await request(`/api/zones/${active.id}`,{method:"DELETE"});setZones(v=>v.filter(z=>z.id!==active.id));setSelected(null)}
  function patch(values:Partial<ZoneConfig>){setZones(v=>v.map(z=>z.id===selected?{...z,...values}:z))}
  return <div className="page"><header className="topbar"><div><p className="eyebrow">SPATIAL INTELLIGENCE</p><h1>Zone studio</h1></div><div className="top-actions"><button className="button ghost" onClick={reset}><RotateCcw size={17}/>Reset</button><button className="button primary" disabled={saving} onClick={save}><Save size={17}/>{saving?"Saving…":"Save layout"}</button></div></header>
    <div className="editor-layout"><section className="editor-canvas panel"><div className="panel-heading"><div><MousePointer2 size={18}/><div><strong>Drag zones into position</strong><small>Coordinates are normalized across camera resolutions</small></div></div><button className="icon-button" onClick={add} aria-label="Add zone"><Plus/></button></div><div className="canvas-feed">{cameraConnected?<img src={`${apiBase}/api/camera/stream`} alt="Camera preview for zone editing"/>:<div className="hardware-offline"><strong>Physical camera required</strong><span>Zone editing resumes when the live camera reconnects.</span></div>}{cameraConnected?zones.map(zone=>{const xs=zone.coordinates.map(p=>p.x),ys=zone.coordinates.map(p=>p.y);return <button key={zone.id} aria-label={`Move ${zone.name}`} className={`zone-shape ${selected===zone.id?"selected":""}`} onPointerDown={e=>pointerDown(e,zone.id)} onPointerMove={pointerMove} onPointerUp={pointerUp} style={{left:`${Math.min(...xs)*100}%`,top:`${Math.min(...ys)*100}%`,width:`${(Math.max(...xs)-Math.min(...xs))*100}%`,height:`${(Math.max(...ys)-Math.min(...ys))*100}%`,borderColor:zone.colour,background:`${zone.colour}22`}}><span style={{background:zone.colour}}>{zone.name}</span></button>}):null}</div></section>
      <aside className="inspector panel"><div className="panel-heading"><div><strong>Zone inspector</strong><small>{active?`Editing zone ${active.id}`:"Select a zone"}</small></div></div>{active?<div className="form-stack"><label>Name<input value={active.name} onChange={e=>patch({name:e.target.value})}/></label><label>Geometry<select value={active.zone_type} onChange={e=>patch({zone_type:e.target.value as ZoneConfig["zone_type"]})}><option value="rectangle">Rectangle</option><option value="polygon">Polygon</option></select></label><fieldset><legend>Accent colour</legend><div className="palette">{palette.map(c=><button key={c} aria-label={`Use ${c}`} onClick={()=>patch({colour:c})} style={{background:c}}>{active.colour===c&&<Check/>}</button>)}</div></fieldset><label>Relay IDs<input value={active.relay_ids.join(", ")} onChange={e=>patch({relay_ids:e.target.value.split(",").map(Number).filter(Boolean)})}/></label><label className="toggle-row"><span><strong>Automatic control</strong><small>Occupancy drives mapped relays</small></span><input type="checkbox" checked={active.auto_control_enabled} onChange={e=>patch({auto_control_enabled:e.target.checked})}/></label><label className="toggle-row"><span><strong>Zone enabled</strong><small>Include in person assignment</small></span><input type="checkbox" checked={active.enabled} onChange={e=>patch({enabled:e.target.checked})}/></label><button className="danger-text" onClick={remove}><Trash2 size={16}/>Delete zone</button></div>:<div className="empty-state">Select a zone on the preview to edit its settings.</div>}</aside></div>
  </div>;
}
